language: node_js
node_js:
- 11.7.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm i
- npm i -g firebase-tools
script:
- npm run build
- fireabase deploy --token $FIREBASE_TOKEN